# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rainbow", "~> 3.1"

gem "tty-prompt", "~> 0.23.1"

gem "font-awesome-rails", "~> 4.7"

gem "rubocop", "~> 1.26"

gem "ruby-progressbar", "~> 1.11"
