# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rainbow", "~> 3.1"

gem "tty-prompt", "~> 0.23.1"

gem "rubocop", "~> 1.26"

gem "tty-font", "~> 0.5.0"

gem "pastel", "~> 0.8.0"
